version: 0.2

env:
  variables:
    EXPO_DEBUG: true
phases:
  install:
    commands:
      - "curl -X POST -H \"Content-Type: application/json\" -d @./notif/beta/notif_starting.json https://outlook.office.com/webhook/51563557-8ad2-4742-be7a-43e83ceb02fd@d0b5b587-5748-42b1-ab45-fb05919c0998/IncomingWebhook/22533cea3792433e8fcefc9913e38019/cb90240d-bba9-4047-95f6-63773fc8886c"
      - apt-get update
      - apt-get install -y nodejs
      - npm i -g expo-cli
  pre_build:
    commands:
      - expo login -u sinewave -p papitopiernaslargas69 --non-interactive
      - npm i
      - export NODE_OPTIONS=--max_old_space_size=4096
  build:
    commands:
      - "curl -X POST -H \"Content-Type: application/json\" -d @./notif/beta/notif_preparing.json https://outlook.office.com/webhook/51563557-8ad2-4742-be7a-43e83ceb02fd@d0b5b587-5748-42b1-ab45-fb05919c0998/IncomingWebhook/22533cea3792433e8fcefc9913e38019/cb90240d-bba9-4047-95f6-63773fc8886c"
      - expo build:android --no-wait --non-interactive --release-channel beta

  post_build:
    commands:
      - "curl -X POST -H \"Content-Type: application/json\" -d @./notif/beta/notif_sent.json https://outlook.office.com/webhook/51563557-8ad2-4742-be7a-43e83ceb02fd@d0b5b587-5748-42b1-ab45-fb05919c0998/IncomingWebhook/22533cea3792433e8fcefc9913e38019/cb90240d-bba9-4047-95f6-63773fc8886c"